apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
  - name: validate.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE
    clientConfig:
      service:
        name: validate
        namespace: default
        path: /validate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6akNDQXJhZ0F3SUJBZ0lVT0traW1xY0h4SlNoeUZBdzlaTVR1SkY3R2lnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRUxNQWtHQTFVRUJoTUNSMEl4RGpBTUJnTlZCQWdNQlV4cGJtTnpNUTh3RFFZRFZRUUhEQVpNYjI1awpiMjR4RXpBUkJnTlZCQW9NQ2tKeWFXUm5aV055WlhjeER6QU5CZ05WQkFzTUJrUmxkbEpsYkRFUU1BNEdBMVVFCkF3d0hSMmxuWjJsMGVUQWVGdzB5TVRFd01UTXdORE15TWpaYUZ3MHlOREE0TURJd05ETXlNalphTUdZeEN6QUoKQmdOVkJBWVRBa2RDTVE0d0RBWURWUVFJREFWTWFXNWpjekVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUk13RVFZRApWUVFLREFwQ2NtbGtaMlZqY21WM01ROHdEUVlEVlFRTERBWkVaWFpTWld3eEVEQU9CZ05WQkFNTUIwZHBaMmRwCmRIa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQzJHUWFGNGVhd3EvczR0ODkKTWc0L3ZUQ21xOUtuQ1p0cldpTkZHemd6QllLODRnS0hZaTJwcmhmcTZNMThjTHNvcWJZOGdqRmwwcE9jakVCWgpvekw0by8zTXl6UGpsL3cwUkxvNElsSmU1UExvdzFvbGE5c29sWTcyOTZRVW9zK0wzdnBrTjB2UjV2ZGtxUzlmCkg1dzlDWGtBV1dNVFpyNkNBZDgwMmNtd09HM1lxNWtwZ2RnclNWbCsrU21WcC81YlZSMHhFTGp1YVpwcEk2VGMKcTdaTTNOdmMwckNEN0YwSEU0aWNPc2czTys1dWVQTGZLd21ub1VMaWFCeG5VaXZ4ekpiVEp1SnJXUyt6dlpNTApUZ2xuUDgrY3owbEt3SDNUN1ppajB1dTdQYjVuRldxMEV4ekNnZ1h6VUpRYWpSZnJTajBvMjdORU93ZTZlZGJ2CmZkSEpBZ01CQUFHamREQnlNQjBHQTFVZERnUVdCQlN0My9MRXdTczRHdXdYbDE5MkVqS040WTRhZFRBZkJnTlYKSFNNRUdEQVdnQlN0My9MRXdTczRHdXdYbDE5MkVqS040WTRhZFRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUI4RwpBMVVkRVFRWU1CYUNGSFpoYkdsa1lYUmxMbVJsWm1GMWJIUXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQ3NwMnBIM05mbGRJamJLVW9xckhJOU41QzZqU1JvTUU4STlURHlYaEVVSm9vcU1NZmgzYS9wZVdidStDTDUKemQzK0pNODhjellMZ2J6bFhqLzA0ZmRQaTR1WkVvRms3dlovenNUTFEwWWk3UnpRaTFJTDErMlhGMHJIUGZpcQpOcFFmMi8yanhCYVNzenI2OGYxTkR3VDVTVnNPbXF5SFdZM3drNkR4SEFkcmpRSlcxTUtBeGd5VGN4QWlKYTlvClVkeUh2R1pXWUJoNmJmV1BYM3FNTWgvTmRiRXY1SzYrRGFIMWFKSXY5OWJhUHpPbzN4cWlKdGV2aWx6ZkppeG8KVDZsYk4zUnVnR0pRb3A3dlZzek1PU2Uwc2FHUXpzaDFzMm1JNThId0xjQjJaNmdNTEVPWXZJMHVFTCtFblBSUAptZUFKQVR2aE9zMTIxQS9zTlI5aVBjTlIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
