apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  namespace: bridgecrew
  labels:
    app: validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
      - name: webhook
        image: eurogig/whorf@sha256:6b0ed00955183537c1227b754c4972ea093fd04bb79bce8d02cd278e49251e06
        ports:
        - containerPort: 8443
        env:
        - name: BC_SOURCE
          value: cli
        - name: LABEL
          value: development
        - name: BC_API_KEY
          valueFrom:
            secretKeyRef:
              name: bridgecrew-rt-secret
              key: BC_API_KEY
        - name: REPO_ID
          valueFrom:
            secretKeyRef:
              name: bridgecrew-rt-secret
              key: REPO_ID
        volumeMounts:
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        - name: "config"
          mountPath: "/app/config"
        imagePullPolicy: Always
      volumes:
      - name: certs-volume
        secret:
          secretName: admission-tls
      - name: "config"
        configMap:
          name: "checkovconfig"
